name: Release

on:
  push:
    branches:
      - master
    paths:
      - "lerna.json"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - name: Fetch all tags
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: |
          npm install
      - name: Read version created by Lerna.js
        id: lerna_version
        run: |
          echo "::set-output name=version::v$(npm run version --silent)"
      - name: Check if release tag is already created
        id: vars
        run: |
          lerna_version=${{ steps.lerna_version.outputs.version }}
          if [[ -z $(git tag -l "$lerna_version") ]]; then
            echo "Proceeding to create new release"
          else
            echo "New release already created, exiting."
            exit 1
          fi
      - run: npx lerna bootstrap --hoist
      - run: npm run build --if-present
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.lerna_version.outputs.version }}
          release_name: ${{ steps.lerna_version.outputs.version }}
          body: |
            See CHANGELOG file to see what's changed in new release.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to NPM registry
        run: npx lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
